- name: print the username and password
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: Please Enter the username
    private: false
  - name: password
    prompt: Please Enter the password
    private: true
  tasks:
    ansible.builtin.debug:
      msg: "username is {{ username }}, password is {{ password }}"
    
